goals_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]

  resources :goals, only: [:index]
end

goals_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goals_app/app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, :goal_id, :body, presence: true

  belongs_to :goal
  belongs_to :user 
end

goals_app/app/models/goal.rb
class Goal < ApplicationRecord
  validates :user_id, :title, :body, presence: true

  belongs_to :user
  has_many :comments 
end

goals_app/app/models/user.rb
class User < ApplicationRecord
  before_validation :ensure_session_token

  validates :username, :email, presence: true, uniqueness: true
  validates :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_many :goals
  has_many :comments

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(password)
    bcrypt_pw = BCrypt::Password.new(self.password_digest)
    bcrypt_pw.is_password?(password)
  end
end

goals_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

goals_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
end

goals_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ['Invalid Credentials']
      render :new
    end
  end

  def destroy
    logout!
    redirect_to goals_url
  end
end

goals_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      flash[:errors] = ['User could not be found']
      redirect_to goals_url
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, status: 422
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
    render :edit
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
    redirect_to goals_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

goals_app/app/helpers/application_helper.rb
module ApplicationHelper
end

goals_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">
        <input type="submit" name="" value="Logout">
      </form>
    <% else %>
      <form action="<%= new_session_url %>" method="get">
        <input type="submit" name="" value="Login">
      </form>

      <form action="<%= new_user_url %>" method="get">
        <input type="submit" name="" value="Signup">
      </form>
    <% end %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

goals_app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input id='user_username' type="text" name="user[username]" value="">

  <label for="user_email">Email</label>
  <input id='user_email' type="text" name="user[email]" value="">

  <label for="user_password">Password</label>
  <input id='user_password' type="text" name="user[password]" value="">


  <input type="submit" name="" value="Sign up">

</form>

goals_app/app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>
<br>

<div class="">
  <h4>Username: </h4>
  <p><%= @user.username %></p>

  <h4>Email: </h4>
  <p><%= @user.email %></p>
</div>